name = "background.ppm"
type = "ppm"
codification = "ascii" -- aqui poderia ser: ascii
width = 400
height = 400
upper_left  = { 0, 1, 0 } -- Cor do canto superior esquerdo (verde)
lower_left  = { 0, 0, 0 } -- Cor do canto inferior esquerdo (preto)
upper_right = { 1, 1, 0 } -- Cor do canto superior direito (amarelo)
lower_right  = { 1, 0, 0 } -- Cor do canto inferior direito (vermelho)
